spring:
  profiles:
    active: dev
---
server:
  port: 8080
spring:
  profiles: dev
  application:
    name: concumenr

---
spring:
  application:
    name: consumer1
  profiles: test
server:
  port:8081